ARG TEST_BASE_IMAGE=turbojam:test-base

FROM ${TEST_BASE_IMAGE} AS builder
COPY --chown=dev:dev 3rdparty    /home/dev/turbojam/3rdparty
COPY --chown=dev:dev lib         /home/dev/turbojam/lib
COPY --chown=dev:dev src         /home/dev/turbojam/src
COPY --chown=dev:dev CMakeLists.txt /home/dev/turbojam/

WORKDIR /home/dev/turbojam
RUN cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Coverage -DCMAKE_CXX_COMPILER=clang++-19 \
    && cmake --build build -t tjam-test

FROM ${TEST_BASE_IMAGE} AS runtime
WORKDIR /home/dev/turbojam
COPY --from=builder --chown=dev:dev /home/dev/turbojam/build ./build
COPY --chown=dev:dev data ./data
COPY --chown=dev:dev etc ./etc

CMD ["/bin/bash"]
