FROM ubuntu:24.04 AS builder
LABEL MAINTAINER="R2 Rationality <info@r2rationality.com>"
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    tzdata curl ca-certificates gnupg2 \
    build-essential cmake pkg-config git zstd ninja-build \
    libnuma-dev \
    libboost-json1.83-dev \
    libboost-url1.83-dev \
    libboost-coroutine1.83-dev \
    libboost-thread1.83-dev \
    libboost-stacktrace1.83-dev \
    libsodium-dev libsecp256k1-dev libzstd-dev libssl-dev \
    libfmt-dev libspdlog-dev libbotan-2-dev liblmdb-dev \
    clang-19 clang-tools-19 llvm-19 libclang-rt-19-dev \
    && ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash -d /home/dev dev
USER dev
WORKDIR /home/dev

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
ENV PATH=/home/dev/.cargo/bin:$PATH

RUN install -d -o dev -g dev /home/dev/turbojam/
COPY --chown=dev:dev 3rdparty    /home/dev/turbojam/3rdparty
COPY --chown=dev:dev data        /home/dev/turbojam/data
COPY --chown=dev:dev etc         /home/dev/turbojam/etc
COPY --chown=dev:dev lib         /home/dev/turbojam/lib
COPY --chown=dev:dev src         /home/dev/turbojam/src
COPY --chown=dev:dev CMakeLists.txt /home/dev/turbojam/

WORKDIR /home/dev/turbojam
RUN rm -rf 3rdparty/msquic/bld 3rdparty/msquic/build \
    && cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Coverage -DCMAKE_CXX_COMPILER=clang++-19 \
    && cmake --build build -t tjam-test

FROM ubuntu:24.04 AS runtime
LABEL MAINTAINER="R2 Rationality <info@r2rationality.com>"
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    tzdata sudo \
    clang-tools-19 llvm-19 \
    libnuma1 \
    libboost-json1.83 \
    libboost-url1.83 \
    libboost-coroutine1.83 \
    libboost-thread1.83 \
    libboost-stacktrace1.83 \
    libsodium23 libsecp256k1-1 libzstd1 libssl3 \
    libfmt9 libspdlog1.12 libbotan-2-19 liblmdb0 \
    && ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && awk '{ if (/^%sudo/) { print "%sudo\tALL=(ALL:ALL) NOPASSWD:ALL" } else { print } }' /etc/sudoers > /tmp/sudoers.tmp \
    && mv /tmp/sudoers.tmp /etc/sudoers \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash -d /home/dev -G sudo dev
USER dev

RUN install -d -o dev -g dev /home/dev/turbojam/log
WORKDIR /home/dev/turbojam
COPY --from=builder --chown=dev:dev /home/dev/turbojam/build ./build
COPY --from=builder --chown=dev:dev /home/dev/turbojam/data ./data
COPY --from=builder --chown=dev:dev /home/dev/turbojam/etc ./etc

CMD ["/bin/bash"]
