FROM ubuntu:24.04
LABEL MAINTAINER="R2 Rationality <info@r2rationality.com>"
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    tzdata sudo curl ca-certificates gnupg2 \
    build-essential cmake pkg-config git zstd ninja-build \
    libnuma-dev \
    libboost-json1.83-dev \
    libboost-url1.83-dev \
    libboost-coroutine1.83-dev \
    libboost-thread1.83-dev \
    libboost-stacktrace1.83-dev \
    libsodium-dev libsecp256k1-dev libzstd-dev libssl-dev \
    libfmt-dev libspdlog-dev libbotan-2-dev liblmdb-dev \
    libngtcp2-dev libngtcp2-crypto-gnutls-dev libgnutls28-dev \
    clang-19 clang-tools-19 llvm-19 libclang-rt-19-dev \
    && ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && awk '{ if (/^%sudo/) { print "%sudo\tALL=(ALL:ALL) NOPASSWD:ALL" } else { print } }' /etc/sudoers > /tmp/sudoers.tmp \
    && mv /tmp/sudoers.tmp /etc/sudoers \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash -d /home/dev -G sudo dev
USER dev
WORKDIR /home/dev

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
ENV PATH=/home/dev/.cargo/bin:$PATH

RUN install -d -o dev -g dev /home/dev/turbojam/log
WORKDIR /home/dev/turbojam

CMD ["/bin/bash"]
