FROM ubuntu:24.04
LABEL MAINTAINER "R2 Rationality <info@r2rationality.com>"
ENV DEBIAN_FRONTEND=noninteractive

RUN mv /etc/apt/sources.list /etc/apt/sources.list.orig
RUN sed 's/archive.ubuntu.com/de.archive.ubuntu.com/g' /etc/apt/sources.list.orig > /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y tzdata screen vim-nox dnsutils iputils-ping net-tools curl wget sudo strace gnupg2
RUN ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime
RUN dpkg-reconfigure --frontend noninteractive tzdata
RUN cp /etc/sudoers /etc/sudoers.orig
RUN awk '{ if (/^%sudo/) { print "%sudo\tALL=(ALL:ALL) NOPASSWD:ALL" } else { print } }' /etc/sudoers.orig > /etc/sudoers
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 31F54F3E108EAD31
RUN apt-get update
RUN apt-get install -y build-essential cmake pkg-config git gdb mc
RUN /bin/bash -c '/bin/bash <(curl -sL https://deb.nodesource.com/setup_20.x)'
RUN apt-get install -y nodejs zstd valgrind gcovr
RUN apt-get install -y pv gawk telnet whois
RUN apt-get install -y libboost1.83-all-dev libboost-url1.83-dev libsodium-dev libsecp256k1-dev libzstd-dev libssl-dev libfmt-dev libspdlog-dev libbotan-2-dev
RUN apt-get install -y jq ninja-build clang-19 clang-tools-19
RUN apt-get install -y jq libsecp256k1-dev libgoogle-perftools-dev google-perftools
RUN apt-get install -y jq sloccount
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN mkdir -p /home/dev
RUN useradd -m -s /bin/bash -d /home/dev -G sudo dev
RUN chown -R dev:dev /home/dev
COPY docker-dev.sh /home/dev

USER dev
ENV NODE_PATH=/usr/lib/node_modules
WORKDIR /home/dev
EXPOSE 8888
CMD [ "/bin/bash", "/home/dev/docker-dev.sh" ]
