FROM ubuntu:24.04
LABEL MAINTAINER="R2 Rationality <info@r2rationality.com>"
ENV DEBIAN_FRONTEND=noninteractive

RUN sed -i 's/archive.ubuntu.com/de.archive.ubuntu.com/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    tzdata ca-certificates curl wget sudo gnupg2 \
    screen vim-nox dnsutils iputils-ping net-tools strace \
    build-essential cmake pkg-config git gdb mc ninja-build \
    zstd valgrind gcovr pv gawk telnet whois jq \
    clang-19 clang-tools-19 \
    libboost1.83-all-dev libboost-url1.83-dev \
    libsodium-dev libsecp256k1-dev libzstd-dev libssl-dev \
    libfmt-dev libspdlog-dev libbotan-2-dev liblmdb-dev \
    libngtcp2-dev libngtcp2-crypto-gnutls-dev libgnutls28-dev \
    libgoogle-perftools-dev google-perftools \
    sloccount texlive-full docker.io \
    && ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && awk '{ if (/^%sudo/) { print "%sudo\tALL=(ALL:ALL) NOPASSWD:ALL" } else { print } }' /etc/sudoers > /tmp/sudoers.tmp \
    && mv /tmp/sudoers.tmp /etc/sudoers \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get update \
    && apt-get install -y --no-install-recommends nodejs \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash -d /home/dev -G sudo,docker dev
COPY docker-dev.sh /home/dev/docker-dev.sh
RUN chown -R dev:dev /home/dev

USER dev
ENV NODE_PATH=/usr/lib/node_modules
ENV PATH=/home/dev/.cargo/bin:$PATH
WORKDIR /home/dev
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal

EXPOSE 8888
CMD ["/bin/bash", "/home/dev/docker-dev.sh"]
